# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E_f1kQ4oZg4DXrA658sMbdWEx6GwVvyZ
"""

def get_soma(n1, n2):
  return n1 + n2

resultado = get_soma(5,3)
print(resultado)
